FROM node:20-bullseye

WORKDIR /app

# Expo CLI。
RUN npm install -g expo-cli

# COPY package.json tsconfig.json app.json ./
COPY app/ /app/
# RUN npx expo install react-dom react-native-web @expo/metro-runtime
# RUN npm install

# compose
