title: "standard_react_fastapi_environment"
description: "a full-stack development environment"
baseurl: "/standard_react_fastapi_environment"
url: "https://europanite.github.io"
theme: minima
plugins:
  - jekyll-sitemap