FROM python:3.12-slim

WORKDIR /root

COPY requirements.txt requirements.test.txt ./
RUN pip install --no-cache-dir -r requirements.txt -r requirements.test.txt

WORKDIR /app

CMD ["pytest","-q","--maxfail=1","--disable-warnings"]
