FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt requirements.test.txt ./

RUN pip install --no-cache-dir -r requirements.txt -r requirements.test.txt

COPY app/ ./

CMD ["pytest","-q","--maxfail=1","--disable-warnings"]
